// Auto-generated by scripts/compile-media-assets.mjs
// Do not edit manually.
// Cleared 2026-03-01: All local GPU-generated assets (217 videos, 2181 images)
// deleted due to persistent anatomy artifacts (hands/fingers). Media will be
// regenerated via cloud providers (DALL-E 3, Runway, etc.) with proper QA.

export type MediaAsset = {
  url: string;
  type: string;
  alt: string;
};

export const GENERATED_MEDIA_ASSETS: Record<string, MediaAsset> = {};
